config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', :to => 'players#new'
  get '/game/:id', :to => 'games#show'
  resources :players
  get '/deploy/board/:board_id', :to => 'games#deploy_fleet', as: 'deploy'
  post 'place/board/:board_id', controller: 'ships', action: :place, as:"place_ships"
  get '/play/:game_id', :to => 'games#play'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :game, counter_cache: :player_count
  belongs_to :player
  has_many :ships
  has_many :spaces

  def generate_player_game
    Ship.create_fleet(self)
    Space.create_spaces(self)
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :boards
  has_many :players, through: :boards
  has_one :winner, class_name: :Player, foreign_key: :winner_id
  def self.open_games
    games = self.all
    game.players 
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :boards
  has_many :games, through: :boards
  has_one :board
  has_many :ships
  
end

app/models/ship.rb
class Ship < ApplicationRecord
  has_many :spaces
  belongs_to :board

  def self.create_fleet(board)
    fleet = []
    lengths = [2,3,3,4,5]
    lengths.each do |length|
      fleet << Ship.create(length: length, board_id: board.id, sunk: false)
    end
    fleet
  end

  def place_ship(length, ship_spaces)
    ship_spaces.each do |space| 
      space.ship = self
      space.save
    end
  end

  def self.all_ships_placed?(board)
    ships = self.where("board_id = #{board.id}")
    ships.all? { |ship| ship.spaces != [] }
  end
  
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :board
  belongs_to :ship, optional: true  
  
  L_TO_N = {"A": 0, 
            "B": 1,
            "C": 2,
            "D": 3,
            "E": 4,
            "F": 5,
            "G": 6,
            "H": 7,
            "I": 8,
            "J": 9
            }
  def self.coordinate_helper
  coordinates = [] 
    (0..9).to_a.each do |col_num|
      (0..9).to_a.each do |row_num|
        coordinates << "#{col_num}#{row_num}"
      end
    end
    coordinates
  end

  def self.create_spaces(board)
    status = "empty"
    coordinates = self.coordinate_helper
    coordinates.each do |coordinate|
      board.spaces << Space.create(status: status, coordinate: coordinate)
      board.save
    end
  end

  def self.get_ship_spaces(board, starting_letter, starting_number, direction, length)
    col = L_TO_N[starting_letter.to_sym]
    row = starting_number.to_i - 1
    first_space = Space.where(board_id: board.id, coordinate: "#{row}#{col}")
    spaces = [first_space]
    if direction == "up"
      (length-1).times do 
        row -= 1
        next_space = Space.where(board_id: board.id,coordinate: "#{row}#{col}")
        spaces << next_space
      end
    elsif direction == "down"
      (length-1).times do 
        row += 1
        next_space = Space.where(board_id: board.id,coordinate: "#{row}#{col}")
        spaces << next_space
      end
    elsif direction == "right"
      (length-1).times do 
        col += 1
        next_space = Space.where(board_id: board.id,coordinate: "#{row}#{col}")
        spaces << next_space
      end
    elsif direction == "left"
        (length-1).times do 
        col -= 1
        next_space = Space.where(board_id: board.id,coordinate: "#{row}#{col}")
        spaces << next_space
      end 
    end
    spaces_are_invalid = spaces.any? { |space| space == [] }
    if spaces_are_invalid
      spaces = [nil]
    else
      return spaces
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    @games = Game.all
  end

  def deploy_fleet
    @board = Board.find(get_params[:board_id])
    @ships = @board.ships.order(length: :desc)
  end

  def play
    @game = Game.find(get_params[:game_id])
  end


  private
  def get_params
    params.permit(:board_id, :game_id)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def new 
    @games = Game.all
    @player = Player.new
  end

  def create
    @player = Player.new(username: player_params[:username])
    if @player.save
      if player_params[:game_id]
        game_id = player_params[:game_id]
        @board = Board.create(player: @player, game_id: game_id)
        @board.generate_player_game
        # render 'games/deploy_fleet'
        redirect_to "/deploy/board/#{@board.id}"
      else
        game = Game.create()
        @board = Board.create(player: @player, game: game)
        @board.generate_player_game
        # render 'games/deploy_fleet'
        redirect_to "/deploy/board/#{@board.id}"
      end
    else 
      @errors = @player.errors.full_messages
      render :new
    end
  end

  private

  def player_params
    params.require(:player).permit(:username, :game_id)
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  def place
    @board = Board.find(place_ship_params[:board_id])
    length = place_ship_params[:ship_length].to_i
    ship = @board.ships.where("length = #{length}")[0]
    if Ship.all_ships_placed?(@board)
      game = @board.game
      redirect_to("/play/#{game.id}")
    else
      if !ship
        flash[:select_ship] = "Please select a ship!"
      elsif ship.spaces != []
        ship = @board.ships.where("length = #{length}")[1]
        ship_spaces = Space.get_ship_spaces(@board, place_ship_params[:letter_start], place_ship_params[:number_start], place_ship_params[:direction], length)
        if ship_spaces.length == ship.length
          ship_spaces.each do |space|
            ship.spaces << space[0]
            space[0].status = 'ship'
            space[0].save
          end
        else
          flash[:invalid_location] = "INVALID CHOICE. SHIP WOULD BE OUT OF BOUNDS."
        end
      else
        ship_spaces = Space.get_ship_spaces(@board, place_ship_params[:letter_start], place_ship_params[:number_start], place_ship_params[:direction], length)
        if ship_spaces.length == ship.length
          ship_spaces
          ship_spaces.each do |space|
            ship.spaces << space[0]
            space[0].status = 'ship'
            space[0].save
          end
        else 
          flash[:invalid_location] = "INVALID CHOICE! SHIP WOULD BE OUT OF BOUNDS!"
        end
      end
      redirect_back(fallback_location: "deploy/board/#{@board.id}") 
    end
  end

  private
  def place_ship_params
    params.permit(:letter_start, :number_start, :direction, :board_id, :ship_length)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_board.html.erb
<div class='fix'>
  <div class="test-2">
    <% nums = (0..10).to_a.each do |num| %>
      <div class="block label" id="num-label"><div class="overlay-box"><%= num %></div></div>
    <% end %>
  </div>
  <div class="test">
    <% letters = ("A".."J").to_a.each do |letter| %>
      <div class="block label" id="letter-label"><div class="overlay-box"><%= letter %></div></div>
    <% end %>
    <% board.spaces.order(:coordinate).each do |space| %>
      <% if space.status == 'empty' %>
        <div class="block" id="test-block"><div class="overlay-box"></div></div>
      <% elsif space.status == 'ship' %>
        <div class="block" id="test-ship-block"><div id="test-ship-block"></div></div>
      <% elsif space.status == 'miss' %>
        <div class="block" id="test-hit-block"><div class="overlay-box"></div></div>
      <% elsif space.status == 'hit' %>
        <div class="block" id="test-miss-block"><div class="overlay-box"></div></div>
      <% else %>
        <div class="block" id="test-block"><div class="overlay-box"></div></div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/_ship_row.html.erb
<div class="length"><div class="dot"></div></div>

app/views/games/deploy_fleet.html.erb
<div class='place-ships-board'>
  <h2>Deploy your ships below!</h2>
  <%= render partial: 'games/board', locals: {board: @board}%>
</div>

<div id="ship-box">
  <h2>Click on a ship to place it!</h2>
  <% @ships.each do |ship| %>
    <% if ship.spaces == []  %>
      <div data-ship-length='<%= ship.length %>' data-ship-id='<%= ship.id %>' class="ship">
        <% ship.length.times do %>
          <%= render partial: 'games/ship_row' %>
        <% end %>        
      </div>
    <% end %>
  <% end %>
  <br>
  <div id="starting-position">
    <% if flash[:select_ship] %>
      <div class="error">
        <%= flash[:select_ship] %>
      </div>
    <% end %>
    <% if flash[:invalid_location] %>
      <div class="error">
        <%= flash[:invalid_location] %>
      </div>
    <% end %>
    <%= form_tag(place_ships_path, method: "post") do %>
      <% if Ship.all_ships_placed?(@board) %>
        <%= submit_tag "LET'S PLAY!!!!!!" %>
      <% else %>
        <span>Choose your starting position</span>
        <%= select_tag 'letter_start', options_for_select(("A".."K").to_a) %>
        <%= select_tag 'number_start', options_for_select((1..10).to_a) %>
        <br>
        <span>And your direction</span>
        <%= select_tag 'direction', options_for_select(["up", "down", "left", "right"]) %>
        <%= hidden_field_tag "ship_length" %>
        <br>
        <%= submit_tag "Place!" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/play.html.erb
<h2>TEST</h2>

app/views/games/show.html.erb
<div class="game">
  <div class="player-one">
    <%= render partial: 'games/board' %>
  </div>
  <br>
  <div class="player-two">
    <%= render partial: 'games/board' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Battleship</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'welcome', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'board', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'place-ships', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Arimo|Bubbler+One" rel="stylesheet">
  </head>

  <body>
  <nav>
    <h1>BATTLESHIP</h1>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/players/new.html.erb
<center>
  <div class="new-game-box">
    <h2>Start a new game</h2>
    <div class="form-group">
      <%= form_for @player do |f| %>
        username: <%= f.text_field :username, class: "form-input" %>
        <%= f.submit "PLAY!", class: 'play-button' %>
      <% end %>
      <% if @errors %>
      <p class="error"><%= @errors %></p>
      <% end %>
    </div>
  </div>
  <div class="join-game-box">
    <h2>Join a game</h2>
    <div class='form-group'>
      <h5>here are all of the current games!</h5>
      <% @games.each do |game| %>
        <ul>
        <% if game.players.count == 1 %>
          <li class="current-games"> <%= "Play with:  #{game.players[0].username}" %> 
            <%= form_for @player do |f| %>
              <%= f.hidden_field :game_id, value: game.id %>
              username: <%= f.text_field :username, class: "form-input" %>
            <%= f.submit "PLAY!", class: 'play-button' %>
            <% end %>
          </li>
        <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</center>